import { expect, test } from "@playwright/test";
import { runManifest } from "./run-manifest";
import { retainedPass, signInThroughApi } from "./auth-helpers";

test("catalog values, material drafts and revision history persist through restart", async ({ page }) => {
  await signInThroughApi(page);
  const fixture = runManifest.state.content; const path = `/api/materials/${fixture.id}`;
  if (!retainedPass) {
    await page.goto("/catalog");
    await page.getByLabel("Catalog value", { exact: true }).fill("E2E Natural Stone");
    await page.getByLabel("New abbreviation", { exact: true }).fill("E2E_STONE");
    await page.getByRole("button", { name: "Create catalog value" }).click();
    await expect(page.getByRole("table").getByText("E2E Natural Stone", { exact: true })).toBeVisible();
    await page.getByRole("searchbox", { name: "Search catalog" }).fill("E2E_STONE");
    await expect(page.getByRole("table").getByRole("row")).toHaveCount(2);
    await page.getByRole("searchbox", { name: "Search catalog" }).fill("");
    await page.getByRole("combobox", { name: "Value type", exact: true }).selectOption("collections");
    await page.getByRole("combobox", { name: "Collection brand", exact: true }).selectOption(runManifest.state.brandId);
    await page.getByLabel("Catalog value", { exact: true }).fill("E2E Architectural Series");
    await page.getByLabel("New abbreviation", { exact: true }).fill("E2E_SERIES");
    await page.getByRole("button", { name: "Create catalog value" }).click();
    await expect(page.getByRole("table").getByText("E2E Architectural Series", { exact: true })).toBeVisible();
    await page.goto(`/materials/${fixture.id}`);
    let panel = page.getByRole("article", { name: "Publication content", exact: true });
    await panel.getByRole("textbox", { name: "Description", exact: true }).fill("Synthetic material for catalog verification.");
    await panel.getByRole("spinbutton", { name: "Credits", exact: true }).fill("8");
    await panel.getByRole("textbox", { name: "Tags, one per line", exact: true }).fill("matte\nMatte\nstone");
    await panel.getByRole("checkbox", { name: "E2E_STONE · E2E Natural Stone", exact: true }).check();
    await panel.getByRole("checkbox", { name: "E2E_SERIES · E2E Architectural Series", exact: true }).check();
    await panel.getByLabel("Reason for content change").fill("Classify synthetic E2E material");
    await panel.getByRole("button", { name: "Save publication draft" }).click();
    await expect(panel.getByText(/Revision 1 · Saved content/)).toBeVisible();
    panel = page.getByRole("article", { name: "Publication content", exact: true });
    await panel.getByRole("spinbutton", { name: "Credits", exact: true }).fill("12");
    await panel.getByLabel("Reason for content change").fill("Adjust synthetic credits");
    await panel.getByRole("button", { name: "Save publication draft" }).click();
    await expect(panel.getByText(/Revision 2 · Saved content/)).toBeVisible();
    await page.goto("/catalog");
    for (const action of ["Deactivate", "Reactivate"]) {
      await page.getByLabel("Reason for catalog change").fill(`${action} synthetic category`);
      await page.getByRole("combobox", { name: "Active for E2E Natural Stone", exact: true }).selectOption(action === "Deactivate" ? "false" : "true");
      await expect(page.getByRole("combobox", { name: "Active for E2E Natural Stone", exact: true })).toHaveValue(action === "Deactivate" ? "false" : "true");
      await expect(page.getByLabel("Reason for catalog change")).toBeEnabled();
    }
    await page.goto(`/materials/${fixture.id}`);
    const approval = page.getByRole("article", { name: "Content approval", exact: true });
    await approval.getByRole("button", { name: "Review saved content", exact: true }).click();
    await expect(approval.getByRole("region", { name: "Saved content to approve" })).toContainText("Synthetic material for catalog verification.");
    await approval.screenshot({ path: test.info().outputPath("content-review.png") });
    await approval.getByRole("button", { name: "Confirm content approval", exact: true }).click();
    await expect(approval.getByText("Current content is approved.", { exact: true })).toBeVisible();
    panel = page.getByRole("article", { name: "Publication content", exact: true });
    await expect(panel.getByText(/Revision 2 · Saved content/)).toBeVisible();
    await panel.getByRole("spinbutton", { name: "Credits", exact: true }).fill("13");
    await panel.getByLabel("Reason for content change").fill("Verify invalidation after approval");
    await panel.getByRole("button", { name: "Save publication draft" }).click();
    await expect(panel.getByText(/Revision 3 · Saved content/)).toBeVisible();
    await expect(approval.getByText("Current content requires approval.", { exact: true })).toBeVisible();
    await approval.getByRole("button", { name: "Review saved content", exact: true }).click();
    await approval.getByRole("button", { name: "Confirm content approval", exact: true }).click();
    await expect(approval.getByText("Current content is approved.", { exact: true })).toBeVisible();
  }
  await page.goto(`/materials/${fixture.id}`);
  const panel = page.getByRole("article", { name: "Publication content", exact: true });
  await expect(panel.getByText(/Revision 3 · Saved content/)).toBeVisible();
  await expect(panel.getByRole("textbox", { name: "Description", exact: true })).toHaveValue("Synthetic material for catalog verification.");
  await expect(panel.getByRole("spinbutton", { name: "Credits", exact: true })).toHaveValue("13");
  await expect(panel.getByRole("textbox", { name: "Tags, one per line", exact: true })).toHaveValue("matte\nstone");
  await expect(panel.getByRole("checkbox", { name: "E2E_STONE · E2E Natural Stone", exact: true })).toBeChecked();
  await expect(panel.getByRole("checkbox", { name: "E2E_SERIES · E2E Architectural Series", exact: true })).toBeChecked();
  await panel.getByText("Content history", { exact: true }).click();
  await panel.getByRole("button", { name: "Load content history" }).click();
  await expect(panel.getByText("Revision 1", { exact: true })).toBeVisible();
  await expect(panel.getByText("Revision 2", { exact: true })).toBeVisible();
  const current = await (await page.request.get(path + "/content")).json();
  expect(current.revision).toBe(3); expect(current.content_status).toBe("APPROVED"); expect(current.collections[0].brand_id).toBe(runManifest.state.brandId);
  expect(current.categories[0].version).toBe(3); expect(current.categories[0].is_active).toBe(true);
  const history = await (await page.request.get(path + "/content-history")).json();
  expect(history).toHaveLength(3); expect(history.map((item: { snapshot: { credits: number } }) => item.snapshot.credits)).toEqual([13, 12, 8]);
  expect((await (await page.request.get(path + "/review")).json()).generation).toBe(5);
  const approvals = await (await page.request.get(path + "/content-approvals")).json();
  expect(approvals).toHaveLength(2); expect(approvals.map((item: { content_revision: number }) => item.content_revision)).toEqual([3, 2]);
  const currentReview = await (await page.request.get(path + "/content-review")).json();
  expect(currentReview.approval.id).toBe(approvals[0].id);
  await expect(page.getByRole("article", { name: "Content approval", exact: true }).getByText("Current content is approved.", { exact: true })).toBeVisible();
  const audit = await (await page.request.get("/api/catalog-audit")).json();
  const ownedIds = [current.categories[0].id, current.collections[0].id];
  expect(audit.filter((item: { resource_id: string }) => ownedIds.includes(item.resource_id))).toHaveLength(4);
  const vocabulary = await (await page.request.get("/api/online-categories")).json();
  expect(vocabulary.find((item: { id: string }) => item.id === current.categories[0].id)).toMatchObject({ abbreviation: "E2E_STONE", created_at: expect.any(String) });
  const collections = await (await page.request.get("/api/collections")).json();
  expect(collections.find((item: { id: string }) => item.id === current.collections[0].id)).toMatchObject({ abbreviation: "E2E_SERIES", created_at: expect.any(String) });
});
