import { expect, test } from "@playwright/test";
import { runManifest } from "./run-manifest";
import { retainedPass, signInThroughApi } from "./auth-helpers";

test("rebrand and single-confirm Done rename update real files and JSON through restart", async ({ page }) => {
  await signInThroughApi(page);
  const fixture = runManifest.state.identity; const path = `/api/materials/${fixture.id}`;
  const session = await (await page.request.get("/api/auth/session")).json();
  const headers = { Origin: runManifest.frontendUrl, "X-CSRF-Token": session.csrf_token };
  const renamed = "E2E-CONTROLLED-IDENTITY-20-08-RENAMED", renamedIdentity = `E2E_NEXT_0001_${renamed}_G02`;
  if (!retainedPass) expect((await page.request.post(path + "/folder-link", { headers, data: { folder_path: fixture.relativePath } })).status()).toBe(200);
  const before = await (await page.request.get(path)).json();
  await page.goto(`/materials/${fixture.id}`);
  const panel = page.getByRole("article", { name: "Material identity" });
  if (!retainedPass) {
    await page.getByRole("combobox", { name: `Published brand for ${before.material_name}`, exact: true }).selectOption(runManifest.state.identityBrandId);
    await panel.getByLabel("Target category code").selectOption("G02");
    await panel.getByRole("button", { name: "Preview identity changes" }).click();
    await expect(panel.getByRole("region", { name: "Identity change preview" })).toBeVisible();
    await expect(panel.getByText("E2E_NEXT_0001_E2E-CONTROLLED-IDENTITY_G02", { exact: true })).toBeVisible();
    await expect(panel.getByText(/Confirmation reserves number 1/)).toBeVisible();
    await panel.getByLabel("Reason for identity change").fill("Synthetic E2E rebrand and category correction");
    const response = page.waitForResponse((item) => item.request().method() === "POST" && new URL(item.url()).pathname === path + "/identity-confirm");
    await panel.getByRole("button", { name: "Confirm identity change" }).click();
    const confirmed = await response;
    expect(confirmed.status()).toBe(200); expect((await confirmed.json()).status).toBe("COMPLETED");
    await page.getByRole("dialog", { name: "Change material identity" }).getByRole("button", { name: "Back to materials", exact: true }).click();
    const library = page.getByRole("article", { name: "Publication content", exact: true });
    const color = library.getByRole("combobox", { name: "Color HEX", exact: true });
    await expect(color).toBeEnabled();
    await expect(library.getByRole("spinbutton", { name: "Sample width (cm)", exact: true })).toHaveValue("");
    await expect(library.getByRole("spinbutton", { name: "Sample height (cm)", exact: true })).toHaveValue("");
    await color.click();
    await expect(page.getByRole("option", { name: "#CCCC99", exact: true }).locator(".material-color-swatch")).toHaveCSS("background-color", "rgb(204, 204, 153)");
    await library.screenshot({ path: test.info().outputPath("material-color-swatches.png") });
    await color.press("End"); await color.press("Enter");
    await expect(color).toHaveText(/#666666/);
    await expect(color.locator(".material-color-swatch")).toHaveCSS("background-color", "rgb(102, 102, 102)");
    await library.getByRole("textbox", { name: "Description", exact: true }).fill("Synthetic library content saved with a complete metadata.json and unknown sample sizes.");
    const metadataSaved = page.waitForResponse(item => item.request().method() === "POST" && new URL(item.url()).pathname === path + "/source-metadata");
    await library.getByRole("button", { name: "Save library data", exact: true }).click();
    const saved = await metadataSaved; expect(saved.status()).toBe(200); expect((await saved.json()).status).toBe("COMPLETED");
    await expect(library.getByText(/Revision 1 · Saved content/)).toBeVisible();
    const status = page.getByRole("combobox", { name: `Status for ${before.material_name}`, exact: true });
    await expect(status).toBeEnabled(); await status.selectOption("DONE"); await expect(status).toBeEnabled();
    const checked = page.getByRole("combobox", { name: `Checked for ${before.material_name}`, exact: true });
    await checked.selectOption("OK"); await expect(checked).toBeEnabled();
    await expect(checked).toHaveValue("OK");
    await page.getByRole("button", { name: "Edit Name", exact: true }).click();
    const rename = page.getByRole("dialog", { name: "Edit Name", exact: true });
    await expect(rename.getByRole("button", { name: "Preview changes", exact: true })).toHaveCount(0);
    await expect(rename).toContainText("Checked resets to no");
    await rename.getByRole("textbox", { name: "Material name", exact: true }).fill(renamed.toLowerCase());
    await expect(rename.getByRole("textbox", { name: "Material name", exact: true })).toHaveValue(renamed);
    await rename.screenshot({ path: test.info().outputPath("material-done-rename-confirmation.png") });
    const renamedResponse = page.waitForResponse(item => item.request().method() === "POST" && new URL(item.url()).pathname === path + "/identity-confirm");
    await rename.getByRole("button", { name: "Confirm rename", exact: true }).click();
    const renamedResult = await renamedResponse;
    expect(renamedResult.status()).toBe(200); expect((await renamedResult.json()).status).toBe("COMPLETED");
    await expect(rename).not.toBeVisible();
  }
  await expect(page.getByRole("heading", { name: renamed, exact: true })).toBeVisible();
  await expect(page.getByRole("combobox", { name: `Published brand for ${renamed}`, exact: true })).toHaveValue(runManifest.state.identityBrandId);
  const current = await (await page.request.get(path)).json();
  expect(current.id).toBe(fixture.id); expect(current.project_id).toBe(runManifest.state.projectId);
  expect(current.published_brand_id).toBe(runManifest.state.identityBrandId);
  expect(current.material_name).toBe(renamed); expect(current.technical_identity).toBe(renamedIdentity);
  expect(current.folder_path).toBe("e2e-identity/" + renamedIdentity);
  expect(current.workflow_status).toBe("DONE"); expect(current.checked_status).toBe("no"); expect(current.is_published).toBe(false);
  await expect(page.getByRole("combobox", { name: `Status for ${renamed}`, exact: true })).toHaveValue("DONE");
  await expect(page.getByRole("combobox", { name: `Checked for ${renamed}`, exact: true })).toHaveValue("no");
  const color = page.getByRole("combobox", { name: "Color HEX", exact: true });
  await expect(color).toHaveText(/#666666/);
  await color.press("ArrowDown"); await color.press("Home"); await color.press("Escape");
  await expect(color).toHaveText(/#666666/); await expect(page.getByRole("listbox", { name: "Color HEX choices" })).toHaveCount(0);
  const metadata = await (await page.request.get(path + "/source-metadata")).json();
  expect(metadata.source_filename).toBe("metadata.json");
  expect(metadata.values).toMatchObject({ hex_color: "#666666", width_cm: null, height_cm: null });
  const operations = await (await page.request.get(path + "/identity-operations")).json();
  expect(operations.operations).toHaveLength(2); expect(operations.operations[0].status).toBe("COMPLETED");
  const review = await (await page.request.get(path + "/review")).json();
  const scan = await page.request.post(path + "/inventory/scan", { headers, data: { expected_generation: review.generation, idempotency_key: crypto.randomUUID() } });
  expect(scan.status()).toBe(200);
  const inventory = await (await page.request.get(path + "/inventory")).json();
  expect(inventory.inventory.entries.filter((entry: { path: string }) => entry.path.includes(fixture.technical_identity))).toHaveLength(0);
  expect(inventory.inventory.entries.filter((entry: { path: string }) => entry.path.includes(`E2E_NEXT_0001_${renamed}_`) || entry.path.endsWith(`E2E_NEXT_0001_${renamed}.sbs`))).toHaveLength(4);
  expect(inventory.inventory.entries.some((entry: { path: string }) => entry.path === "metadata.json")).toBe(true);
  expect(inventory.inventory.source_revision_hash).toBe(operations.operations[0].result.target_revision_hash);
  expect((await (await page.request.get(path + "/identity-history")).json())).toHaveLength(2);
  const brand = await (await page.request.get("/api/brands/" + runManifest.state.identityBrandId)).json();
  expect(brand.next_sequence_number).toBe(2);
  expect((await page.request.post(path + "/identity-operations/" + operations.operations[0].id + "/resume", { headers })).status()).toBe(200);
});
